apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../bases/backend
  - ../../bases/frontend
  - ../../bases/cache
  - namespace.yaml
transformers:
  - labels.yaml
vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: podinfo
      apiVersion: v1