apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../bases/backend
- ../../bases/frontend
- ../../bases/cache
- namespace.yaml
transformers:
- labels.yaml
images:
- name: 948094238297.dkr.ecr.ap-northeast-1.amazonaws.com/podinfo
  newTag: latest
