---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "$(SERVICE_NAME).cor.kkv-test.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: http